service: yc-alerts
variablesResolutionMode: 20210326
frameworkVersion: '2'

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: python3.8
  timeout: 60
  environment:
    ALGOLIA_APPLICATION_ID: 45BWZJ1SGC
    ALGOLIA_API_KEY: Zjk5ZmFjMzg2NmQxNTA0NGM5OGNiNWY4MzQ0NDUyNTg0MDZjMzdmMWY1NTU2YzZkZGVmYjg1ZGZjMGJlYjhkN3Jlc3RyaWN0SW5kaWNlcz1ZQ0NvbXBhbnlfcHJvZHVjdGlvbiZ0YWdGaWx0ZXJzPSU1QiUyMnljZGNfcHVibGljJTIyJTVEJmFuYWx5dGljc1RhZ3M9JTVCJTIyeWNkYyUyMiU1RA==
    MONGO_URL: ${ssm:/yc-alerts-mongo-url}
    IFTTT_TOKEN: ${ssm:/yc-alerts-ifttt-token}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
          Resource:
            - Fn::GetAtt: [ BatchesQueue, Arn ]
            - Fn::GetAtt: [ CompaniesQueue, Arn ]
            - Fn::GetAtt: [ DiffsQueue, Arn ]

functions:
  search:
    handler: search.handler
    events:
      - schedule: rate(6 hours)
    environment:
      BATCHES_SQS_URL:
        Ref: BatchesQueue
      DIFFS_SQS_URL:
        Ref: DiffsQueue
  batch:
    handler: batch.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ BatchesQueue, Arn ]
          batchSize: 10
    environment:
      COMPANIES_SQS_URL:
        Ref: CompaniesQueue
      DIFFS_SQS_URL:
        Ref: DiffsQueue
  company:
    handler: company.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ CompaniesQueue, Arn ]
          batchSize: 10
    environment:
      DIFFS_SQS_URL:
        Ref: DiffsQueue
  diff:
    handler: diff.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ DiffsQueue, Arn ]
          batchSize: 10

resources:
  Resources:
    BatchesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: Batches
        VisibilityTimeout: 60
    CompaniesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: Companies
        VisibilityTimeout: 60
    DiffsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: Diffs
        VisibilityTimeout: 60

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin

custom:
  pythonRequirements:
    dockerizePip: non-linux
  prune:
    automatic: true
    number: 1
