service: yc-alerts
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  timeout: 60
  environment:
    ALGOLIA_APPLICATION_ID: 45BWZJ1SGC
    ALGOLIA_API_KEY: NDYzYmNmMTRjYzU4MDE0ZWY0MTVmMTNiYzcwYzMyODFlMjQxMWI5YmZkMjEwMDAxMzE0OTZhZGZkNDNkYWZjMHJlc3RyaWN0SW5kaWNlcz0lNUIlMjJZQ0NvbXBhbnlfcHJvZHVjdGlvbiUyMiU1RCZ0YWdGaWx0ZXJzPSU1QiUyMiUyMiU1RCZhbmFseXRpY3NUYWdzPSU1QiUyMnljZGMlMjIlNUQ=
    MONGO_URL: ${ssm:/yc-alerts-mongo-url~true}
    IFTTT_TOKEN: ${ssm:/yc-alerts-ifttt-token~true}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource:
        - Fn::GetAtt: [ BatchesQueue, Arn ]
        - Fn::GetAtt: [ CompaniesQueue, Arn ]
        - Fn::GetAtt: [ DiffsQueue, Arn ]
        - Fn::GetAtt: [ ErrorsQueue, Arn ]

functions:
  search:
    handler: search.handler
    onError: !GetAtt ErrorsQueue.Arn
    events:
      - schedule: rate(30 minutes)
    environment:
      BATCHES_SQS_URL:
        Ref: BatchesQueue
      DIFFS_SQS_URL:
        Ref: DiffsQueue
  batch:
    handler: batch.handler
    onError: !GetAtt ErrorsQueue.Arn
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ BatchesQueue, Arn ]
          batchSize: 1
    environment:
      COMPANIES_SQS_URL:
        Ref: CompaniesQueue
      DIFFS_SQS_URL:
        Ref: DiffsQueue
  company:
    handler: company.handler
    onError: !GetAtt ErrorsQueue.Arn
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ CompaniesQueue, Arn ]
          batchSize: 1
    environment:
      DIFFS_SQS_URL:
        Ref: DiffsQueue
  diff:
    handler: diff.handler
    onError: !GetAtt ErrorsQueue.Arn
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ DiffsQueue, Arn ]
          batchSize: 1
  error:
    handler: error.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ ErrorsQueue, Arn ]

resources:
  Resources:
    BatchesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: Batches
    CompaniesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: Companies
    DiffsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: Diffs
    ErrorsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: Errors
        VisibilityTimeout: 60

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin

custom:
  pythonRequirements:
    dockerizePip: non-linux
  prune:
    automatic: true
    number: 1